services:
  postgres:
    image: postgres:16-alpine
    container_name: laravel_hris_postgres
    restart: always
    environment:
      # Mengambil nilai dari .env
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_DOCKER_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Gunakan variabel juga di sini agar tetap sinkron
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE} -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: